name: vyasa
# trunk-ignore(yamllint/quoted-strings)
description: "Vyasa"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.10
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  get: ^4.6.6
  flutter_otp_text_field: ^1.1.1
  ionicons: ^0.2.2
  iconsax: ^0.0.8
  flutter_svg: 2.0.10+1 
  dotted_border: ^2.1.0
  carousel_slider: ^4.2.1
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^4.15.5
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  firebase_storage: ^11.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  android: true
  ios: true

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#272727"

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - google_fonts/
   - assets/images/welcome_images/
   - assets/images/splash_images/
   - assets/images/forgot_password/
   - assets/images/demo/
   - assets/images/img/icons/
   - assets/images/img/posts/large/
   - assets/images/img/posts/small/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTProBook.otf
          weight: 200
        - asset: assets/fonts/AvenirLTProRoman.otf
          weight: 300
        - asset: assets/fonts/AvenirLTProMedium.otf
          weight: 400
        - asset: assets/fonts/AvenirLTProHeavy.otf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
