name: vyasa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.11
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/images/logo.png
  image_dark: assets/images/logo.png
  android: true
  ios: true

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#272727"

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/images/welcome_images/
   - assets/images/splash_images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
